name: "Install AWS CLI"
description: "Here we install aws cli"

runs:
  using: composite
  steps:

    - name: Install AWS CLI
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user
