name: "Builds React App"
description: "Builds an Angular App with pnpm and turborepo"

runs:
  using: composite
  steps:

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install and build
      shell: bash
      run: |
        npm install
        npm run build
